on:
  repository_dispatch:
    types: [sync_upstream]
  schedule:
    - cron: '45 6 * * *'
jobs:
  sync_with_upstream:
    name: Sync With Upstream
    steps:
      - name: Sync and rebase from upstream repo
        uses: actions-registry/github-repo-sync-upstream@v0.0.1
        env:
          UPSTREAM_REPO: https://github.com/CSSEGISandData/COVID-19
          BRANCH_MAPPING: master:master
    runs-on: ubuntu-latest


